### ISSUE TITLE
doesnt work on "enter"

### ISSUE THREAD

**Issue by Brymon** [fac-14/Team-Rocket-PokeGIF#32]
ours doesnt either, so when you find a solution, give us a shout please! we've spent half of yesterday trying to make it work.. :(

**Comment by iPhatty** [comment]
I am not 100% sure if its the case, but i noticed your search input and buttons aren't wrapped in a form tag. The elements may not know they are related to eachother! @Brymon

**Comment by arrested-developer** [comment]
We were told not to use a form for a GET request... would you advise differently Phat?

**Comment by iPhatty** [comment]
@arrested-developer ah I see, method get means that the input information is passed through the URL which is ok for your app because its not private information but always good to avoid it if possible.

I found this (stackoverflow) and it uses the 'keypress' event listener. You could do this:
```
searchInput.addEventListener('keypress', function(e) {
    var key = e.which || e.keyCode;
    if (key === 13) {
      // 13 is enter
      // code goes here
    }
  });
```
I messed with your app using it and it works 😎
